services:
  fdua-competition-v2:
    build:
      context: .
    container_name: fdua-competition-v2
    volumes:
      - .:/fdua-competition
    tty: true
    env_file:
      - secrets/.env

  fdua-notebook-v2:
    build:
      context: .
    container_name: fdua-notebook-v2
    volumes:
      - .:/fdua-competition
    tty: true
    command: uv run jupyter lab --ip 0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.disable_check_xsrf=True
    ports:
      - "8888:8888"
    env_file:
      - secrets/.env